### ISSUE TITLE
Failed requirement in iOS

### ISSUE THREAD

**Issue by daniel-gk8** [ACINQ/secp256k1-kmp#110]
Hi,
I am trying to verify signatures in KMM code. When running the code through the Android project all works fine and the signatures are verified. 
But when running the same code in iOS I keep getting the same error: "Failed requirement".
What is the cause of this? How can I fix it?

KMM code:
```
fun verifySignature(signature: ByteArray, message: ByteArray, pubKey: String): Boolean {
        return Secp256k1.verify(signature, message.toByteString().sha256().toByteArray(), Hex.decode("04$pubKey"))
    }

Converters:
@OptIn(ExperimentalForeignApi::class)
fun NSData.toByteArray(): ByteArray = ByteArray(length.toInt()).apply {
    usePinned {
        memcpy(it.addressOf(0), bytes, length)
    }
}

@OptIn(ExperimentalForeignApi::class)
fun ByteArray.toNSData(): NSData = memScoped {
    NSData.create(bytes = allocArrayOf(this@toNSData), size.toULong())
}
```
`

**Comment by sstone** [comment]
This error means that the parameters passed to `Secp256k1.verify` are invalid in a very basic way (wrong size for example). Printing/logging these parameters should be enough to understand what is wrong.
