### ISSUE TITLE
How to compile and use with android studio and xcode?

### ISSUE THREAD

**Issue by bitcard** [ACINQ/secp256k1-kmp#39]
Need compile and debug it use android studio and xcode? is there any document? thanks a lot.

**Comment by sstone** [comment]
The library is built with `gradle` through the provided gradle wrapper (`gradlew`), I'm not sure it can be built from Android Studio or Xcode (?). 
For example, to build the library and make it available on your machine you should run:
``` shell
./gradlew publishToMavenLocal
```
If you're on macos it will create iOS libraries and publish them to your local maven repo.
If you've installed the Android SDK and configured its location in `local.properties` it will create an Android library and publish it to your local maven repo.

To use the library you can have a look at https://github.com/ACINQ/phoenix which includes Android and iOS applications that use [secp256k1-kmp.](https://github.com/ACINQ/secp256k1-kmp)

[secp256k1-kmp.](https://github.com/ACINQ/secp256k1-kmp) is a "standard" Kotlin Multi Platform library, to learn more about how these projects are built and use you should checkout https://kotlinlang.org/docs/multiplatform.html.

**Comment by bitcard** [comment]
> standard" Kotlin Multi Platform library, to learn



> The library is built with `gradle` through the provided gradle wrapper (`gradlew`), I'm not sure it can be built from Android Studio or Xcode (?). For example, to build the library and make it available on your machine you should run:
> 
> ```shell
> ./gradlew publishToMavenLocal
> ```
> 
> If you're on macos it will create iOS libraries and publish them to your local maven repo. If you've installed the Android SDK and configured its location in `local.properties` it will create an Android library and publish it to your local maven repo.
> 
> To use the library you can have a look at https://github.com/ACINQ/phoenix which includes Android and iOS applications that use [secp256k1-kmp.](https://github.com/ACINQ/secp256k1-kmp)
> 
> [secp256k1-kmp.](https://github.com/ACINQ/secp256k1-kmp) is a "standard" Kotlin Multi Platform library, to learn more about how these projects are built and use you should checkout https://kotlinlang.org/docs/multiplatform.html.

Thank you for your guide, I will try it.
