### ISSUE TITLE
Difference between Android and JVM variant

### ISSUE THREAD

**Issue by AnonymousGeekDev** [ACINQ/secp256k1-kmp#42]
Hello maintainers. Thanks for the work you are doing here.
Please, I wanted to know what real difference there is between the Android and JVM variants
of the library. I want to write a library that is based on this one and the answer will help me choose which
direction to take for my library, as it could be used on plain JVM as well as Android.
Thanks again.

**Comment by sstone** [comment]
Both libraries implement the same interface, both include native JNI bindings for secp256k1 (so you don't have to do anything and will benefit from the best, fastest/... secp256k1 implementation you can get). The difference is in how the native bindings are packaged:
- for the plain JVM library, native secp256k1 libraries are included in the jar and loaded at runtime. this does not work on Android and you would have to provide theses native libraries yourself, or use an AAR archive
- for the Android library native secp256k1 libraries are packaged in a AAR archive

=> When you write your app, just use the `fr.acinq.secp256k1:secp256k1-jni-jvm` dependency
When you run your app, add the appropriate runtime dependency (see https://github.com/ACINQ/secp256k1-kmp#jvm-targets--android). If you're building Kotlin Multi Platform apps/libraries the build system should handle this automatically.

**Comment by AnonymousGeekDev** [comment]
Thanks for the info @sstone . One person I know would like to use my library on a JVM platform(I don't know which platform) and I would like to use it on Android. So, maybe I would have to play with Gradle configs somehow, or just make it a multiplatform library.

**Comment by sstone** [comment]
It should work with any build tool (for example we use secp256k1-kmp in https://github.com/ACINQ/eclair/, a scala project built with maven). The only requirement is to select the proper runtime library (JVM, Android, ...).

**Comment by AnonymousGeekDev** [comment]
I see. Thanks!
