### ISSUE TITLE
Creating private keys

### ISSUE THREAD

**Issue by AnonymousGeekDev** [ACINQ/secp256k1-kmp#43]
Hello again. Sorry, I felt that this is a different issue entirely.
I was looking for how to create private keys using the library,
but it seems there is no API for this. Please, how should I proceed?

**Comment by sstone** [comment]
Private keys are basically random 256-bits numbers, providing a random number generator is out of the scope of this library, as it would be context and application dependent.
For most bitcoin applications you would start with a random seed and use a deterministic process to derive private keys.
You can check https://github.com/bitcoinbook/bitcoinbook for more details on how to manage keys, addresses and wallets.

**Comment by AnonymousGeekDev** [comment]
Thanks for the info! :pray:
