### ISSUE TITLE
Add JNI bindings for Linux Arm64 platforms

### ISSUE THREAD

**Issue by sstone** [ACINQ/secp256k1-kmp#44]

**Comment by sstone** [comment]
Kotlin Natrive does not seem to support linux on ARM64 systems yet. It does support macOS/ARM64 but we don't build for this platform yet.

BUT: this should not be a problem as you can easily build your own JNI library from our sources, as explained in our README: 
On your target machine you need to

- compile secp256k1 (use `build.sh` in `/native)
- compile the jni wrapper (use `build.sh` in `/jni/jvm`)
You now copy `libsecp256k1-jni.so` to another directory, or another machine with the same CPU/OS.

To use your own version of `libsecp256k1-jni.so` start eclair with -Dfr.acinq.secp256k1.lib.path` set to the path of the directory where you've copied  `libsecp256k1-jni.so`.

**Comment by sstone** [comment]
https://github.com/ACINQ/secp256k1-kmp/releases/tag/v0.6.3 includes JNI bindings for Linux Arm64.

**Comment by luca992** [comment]
> Kotlin Natrive does not seem to support linux on ARM64 systems yet. It does support macOS/ARM64 but we don't build for this platform yet.

Any timeline for JNI bindings for macos arm64?

**Comment by luca992** [comment]
> > PS. Why only one native target for linuxX64?
> 
> I'm not sure that I understand your question ? native linux is not a recommended production environment, it's just a testing environment. People should use the JVM and JNI bindings which we provide for Linux X64 and arm 64.

I'm more wondering about mac native targets. But, yeah if github CI is the limiting factor, I understand.
