### ISSUE TITLE
About the Hex functions

### ISSUE THREAD

**Issue by AnonymousGeekDev** [ACINQ/secp256k1-kmp#55]
Hello maintainers. 
Today, I was converting a string to a byte array using one of the Hex functions, and it threw an error, because of a dot(.) in the string. Which brings me to my question: are the Hex functions only for use with private and public key encoding/decoding?

Thanks.

**Comment by t-bast** [comment]
You can use the hex functions with any hex string, it's not at all only for keys. But obviously if you pass in a string that isn't hex, this will throw. A dot isn't a valid hex character, so it's expected that the function throws.

**Comment by AnonymousGeekDev** [comment]
Thanks @t-bast .

**Comment by AnonymousGeekDev** [comment]
I think what I meant was whether it could be used for converting any string, but the answer is clear now.

**Comment by t-bast** [comment]
That wouldn't make any sense...?

**Comment by t-bast** [comment]
If you mean that you want to convert a string to bytes, this really depends on the encoding you choose, and for arbitrary strings you can use things like ascii, utf-8, etc depending on what characters are allowed to be present in your encoding. But that's a completely different thing from hex encoding.

**Comment by AnonymousGeekDev** [comment]
Yeah, @t-bast that is what I meant. Sorry for not being clear enough :sweat_smile: . I understand better now, thanks.
