### ISSUE TITLE
On using context.cleanup()

### ISSUE THREAD

**Issue by AnonymousGeekDev** [ACINQ/secp256k1-kmp#56]
Hello maintainers.
In this [particular file](https://github.com/AnonymousGeekDev/kostr/blob/main/kostr-core/src/main/kotlin/ktnostr/crypto/CryptoUtils.kt), I put context.cleanup() in all these functions.
Please, does it make sense to do so?
Thanks.

**Comment by sstone** [comment]
Not like this, the library cannot be used once `context.cleanup()` has been called, you should only do that when you don't need it anymore (or when your program is terminating.

**Comment by AnonymousGeekDev** [comment]
Thanks @sstone
