### ISSUE TITLE
./autogen.sh: No such file or directory

### ISSUE THREAD

**Issue by Dolu89** [ACINQ/secp256k1-kmp#57]
Hello,

I'm not familiar with kotlin and gradle build, but I tried to build this lib using `./gradlew :build` on my mac m1 (because https://github.com/ACINQ/secp256k1-kmp/issues/44#issuecomment-1094812174) and it results in
```

% ./gradlew :build

> Configure project :
Kotlin Multiplatform Projects are an Alpha feature. See: https://kotlinlang.org/docs/reference/evolution/components-stability.html. To hide this message, add 'kotlin.mpp.stability.nowarn=true' to the Gradle properties.

Project property 'kotlin.parallel.tasks.in.project' is deprecated.
By default it depends on Gradle parallel project execution option value.
Warning: Kotlin language settings function 'useExperimentalAnnotation' is deprecated and will be removed in next major releases. Please, use 'optIn' instead.


> Task :native:buildSecp256k1Ios FAILED
build-ios.sh: line 8: ./autogen.sh: No such file or directory

> Task :compileKotlinJvm UP-TO-DATE

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':native:buildSecp256k1Ios'.
> Process 'command 'bash'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 555ms
2 actionable tasks: 1 executed, 1 up-to-date
skipping android build%
```

Any advice for this error? Or is this related to the m1 chip architecture?

Thanks

**Comment by sstone** [comment]
You could be missing the secp256k1 source code which should be in `native/secp256k1`. We use a git submodule for that, when you clone the project you have to run:
```
git submodule init
git submdule update
```

**Comment by adrianhartanto004** [comment]
> You could be missing the secp256k1 source code which should be in `native/secp256k1`. We use a git submodule for that, when you clone the project you have to run:
> 
> ```
> git submodule init
> git submdule update
> ```

Hi @sstone . I've done the steps above and also made sure that the https://github.com/bitcoin-core/secp256k1 (submodule) is pointing on master.

But I'm still having the same issue `:native:buildSecp256k1Ios FAILED` as @Dolu89 .

Thank you

**Comment by sstone** [comment]
Do you get the same error (`build-ios.sh: line 8: ./autogen.sh: No such file or directory`) ? Without more details it's difficult to understand what went wrong.

**Comment by adrianhartanto004** [comment]
> Do you get the same error (`build-ios.sh: line 8: ./autogen.sh: No such file or directory`) ? Without more details it's difficult to understand what went wrong.

Hello @sstone 
It looks like `./autogen.sh: line 3: autoreconf: command not found` error for me.

More error is shown here below:
```
./gradlew :build

> Configure project :
Kotlin Multiplatform Projects are an Alpha feature. See: https://kotlinlang.org/docs/reference/evolution/components-stability.html. To hide this message, add 'kotlin.mpp.stability.nowarn=true' to the Gradle properties.

Project property 'kotlin.parallel.tasks.in.project' is deprecated.
By default it depends on Gradle parallel project execution option value.
Warning: Kotlin language settings function 'useExperimentalAnnotation' is deprecated and will be removed in next major releases. Please, use 'optIn' instead.


> Task :native:buildSecp256k1Ios FAILED
./autogen.sh: line 3: autoreconf: command not found

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':native:buildSecp256k1Ios'.
> Process 'command 'bash'' finished with non-zero exit value 127

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 867ms
2 actionable tasks: 1 executed, 1 up-to-date
building android library
```

**Comment by sstone** [comment]
> It looks like `./autogen.sh: line 3: autoreconf: command not found` error for me.

You need to install the `automake` package.
