### ISSUE TITLE
:native:buildSecp256k1Host Failed on Windows 11

### ISSUE THREAD

**Issue by adrianhartanto004** [ACINQ/secp256k1-kmp#58]
Hello,

I tried to build the library using ./gradlew :build on Windows 11 and it is giving me this error:
```
secp256k1-kmp> ./gradlew :build

> Configure project :
Kotlin Multiplatform Projects are an Alpha feature. See: https://kotlinlang.org/docs/reference/evolution/components-stability.html. To hide this message, add 'kotlin.mpp.stability.nowarn=true' to the Gradle properties.

Project property 'kotlin.parallel.tasks.in.project' is deprecated.
By default it depends on Gradle parallel project execution option value.
Warning: Kotlin language settings function 'useExperimentalAnnotation' is deprecated and will be removed in next major releases. Please, use 'optIn' instead.


> Task :native:buildSecp256k1Host FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':native:buildSecp256k1Host'.
> A problem occurred starting process 'command 'bash''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 800ms
2 actionable tasks: 1 executed, 1 up-to-date
building android library
```
I'm using OpenJDK11 as recommended on the Readme and have also made sure that the submodule is pointing on the master branch.
What I've tried so far is also Invalidate cache and restart, Sync gradle multiple times, Clean and rebuild project.
But it is still giving me this error

Any solution or advice how to fix this problem please?

Thanks!

**Comment by sstone** [comment]
On windows, secp256k1-kmp is built using the [mingw64](https://www.mingw-w64.org/) compiler (like many other cross platform libraries). You can check our Github CI files to see the steps that you must follow (see https://github.com/ACINQ/secp256k1-kmp/blob/master/.github/workflows/test.yml). Basically you must
- install msys2
- install base-devel, autotools,  mingw-w64-x86_64-gcc
- disable android build
- make sure that msys bash is used (we just remove "C:/WINDOWS/system32/bash.EXE")

Please note that this is not needed if you just want to use the library (adding the JVM dependency to your maven/gradle/... project is enough)
