### ISSUE TITLE
CInterop Unresolved Reference but Build successful

### ISSUE THREAD

**Issue by adrianhartanto004** [ACINQ/secp256k1-kmp#59]
Hello!

I'm getting unresolved reference although `./gradlew :build` builds successful and `iOSX64 tests` are working and all green using macos with intel chip.
```
./gradlew :build

> Configure project :
Kotlin Multiplatform Projects are an Alpha feature. See: https://kotlinlang.org/docs/reference/evolution/components-stability.html. To hide this message, add 'kotlin.mpp.stability.nowarn=true' to the Gradle properties.

Project property 'kotlin.parallel.tasks.in.project' is deprecated.
By default it depends on Gradle parallel project execution option value.
Warning: Kotlin language settings function 'useExperimentalAnnotation' is deprecated and will be removed in next major releases. Please, use 'optIn' instead.


BUILD SUCCESSFUL in 1s
15 actionable tasks: 15 up-to-date
building android library
```

## Unresolved Reference

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/50439894/179300718-5c84ad61-2e21-4570-993d-b9b17542c95d.png">

Any idea on how to fix this please?

Thank you

**Comment by sstone** [comment]
These are issues with Intellij IDEA and kotlin native/multiplatform, you can still build, publish and use `secp256k1-kmp` but working with Idea is very tedious atm for cinterop projects. Please note that most users don't need to build `secp256k1-kmp`, it's available for iOS, Android, and the JVM with JNI bindings for Windows, Linux (amd64 and arm64) and Macos (amd64 only for now).

**Comment by sstone** [comment]
This has been fixed with https://github.com/ACINQ/secp256k1-kmp/pull/63, Intellij IDEA will work properly now.
