### ISSUE TITLE
No corresponding function implementation was found

### ISSUE THREAD

**Issue by BatterMan-Li** [ACINQ/secp256k1-kmp#62]
Check the compiled code. The secp256k1_ecdsa_recoverable_signature_serialize_compact function in the corresponding RECOVER directory is not found. Can you add recompile?

**Comment by sstone** [comment]
Yes we do not export this method but I'm not sure that it is needed: I think that you can easily serialize the signature and recovery id yourself and get the same result as  secp256k1_ecdsa_recoverable_signature_serialize_compact ?

**Comment by BatterMan-Li** [comment]
If you don't export this method, I don't know how to serialize the signature and recovery ID. More importantly, I don't know how to get the recovery ID. How can I get the recovery ID? 
The recid is required to use the ecdsaRecover function. If there is no secp256k1_ecdsa_recoverable_signature_serialize_compact function to obtain the recovery ID, you can only loop 0, 1, 2, and 3 to judge the call.
How should I get it if I need it?

grateful

**Comment by sstone** [comment]
Yes we don't export methods to compute the recovery id, but we do export methods to recover public key, which we use to compute the recovery id: for example see https://github.com/ACINQ/lightning-kmp/blob/master/src/commonMain/kotlin/fr/acinq/lightning/payment/PaymentRequest.kt#L110
