### ISSUE TITLE
Unneeded Native libraries in Android app

### ISSUE THREAD

**Issue by KotlinGeekDev** [ACINQ/secp256k1-kmp#66]
Hello maintainers. Thanks for your work.
Please, when analyzing an app I am writing, I discovered that some native libraries were contributing to 41% the size of the app! 
And the native libraries were the libsecp256k1-kmp Windows DLL and MacOS dylib.
Please, is there a way for me to remove those?
Thanks.

**Comment by sstone** [comment]
Can you please share more details: how do you build your app and how do you include the secp256k1 dependency ? Is it a Kotlin KMM project or a standard Android project ? or even better, can you provide a link to your project ? Android apps built with gradle should just need an .aar file which only contains native libs for android platforms (arm64 and x86_64)

**Comment by KotlinGeekDev** [comment]
Also @sstone the issue occurred after I upgraded the library version to 0.7.0, which is quite strange.

**Comment by KotlinGeekDev** [comment]
Oh, nevermind, the issue still exists in version 0.6.4 as well. And for some reason, when removing the proguard rules I added, the app works in debug mode but doesn't in release mode.

**Comment by KotlinGeekDev** [comment]
Please, any updates on how to solve this? Thanks.
cc @sstone

**Comment by sstone** [comment]
What does "it does not work" mean here ? Did your app ever work before ? I suspect that this is a build issue (resources included in a standard JAR should never end up in the actual app, this is what AAR are for) but don't really know how to help you. We do have an android version of phoenix that uses secp256k1-kmp (see https://github.com/ACINQ/phoenix) that you can have a look at.

**Comment by KotlinGeekDev** [comment]
@sstone in debug mode, it includes the code needed to load the library, but in release mode, it seems not to.

**Comment by KotlinGeekDev** [comment]
Also, as for removing the .DLL and .dylib files included in the app, is it due to KMP or Gradle? I can't really understand why it would include those files even though I specifically included the android JNI dependency.

**Comment by KotlinGeekDev** [comment]
Found the root cause! A library I was using, had a dependency on this library, and thus imported all these files. I will notify the maintainer. Thanks for your patience, @sstone. :pray:

**Comment by sstone** [comment]
Thanks, glad you solved the problem!

**Comment by KotlinGeekDev** [comment]
:pray:
