### ISSUE TITLE
iOS simulator target

### ISSUE THREAD

**Issue by TemMax** [ACINQ/secp256k1-kmp#74]
Hello.
Is it possible to build a library for the ios simulator (iosSimulatorArm64)? It could simplify testing many times.

**Comment by sstone** [comment]
I should be easy but I have not tried and only have a very limited experience with iOS.
You would first add the `iosSimulatorArm64 {}` target to the root build file (`build.gradle.kts`), modify `secp256k1CInterop()` to handle a new `iosSimulatorArm65` target, and update build files in the `native` directory to handle the new target (`build.gradle.kts` and possibly `xconfigure.sh`).

**Comment by TemMax** [comment]
@sstone Hi! I've made a [pull request](https://github.com/ACINQ/secp256k1-kmp/pull/79) with this feature. Could you review it, please?

**Comment by TemMax** [comment]
Ping-ping

**Comment by TemMax** [comment]
I have made it in the [fork](https://github.com/TemMax/secp256k1-kmp) and waiting until all targets are available from this repo.

**Comment by kirillzh** [comment]
Sounds like this issue is still not resolved in this repository, could we keep the ticket open please?

**Comment by sstone** [comment]
Yes, OP closed this issue because they have their own solution but we don't yet, we will probably use what they implemented (thanks!) once our next iOS release is out.

**Comment by colbyharrison** [comment]
Another vote for this getting done. We could use it too.
